### ISSUE TITLE
browser client

### ISSUE THREAD

**Issue by mojoaxel** [vadimdemedes/ohcrash-client#14]
I hope you don't mind me opening this issue but i'm searching for an error reporting solution at the moment and ohcrash just look the "clean, lean error tracking machine" I'm searching for ;-)

But the thing is, that I want to track client (browser) errors as well as backend errors. It doesn't looks difficult to do, but is there already something to base my work on?

**Comment by vadimdemedes** [comment]
I don't maintain OhCrash anymore, so I'd recommend using https://sentry.io/. Their product is open-source so you can set it up yourself for free. Thanks for the interest in OhCrash, who knows, maybe it'll be alive some day again!
