### ISSUE TITLE
Allow setting app's environment

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ohcrash-client#4]

**Comment by leewaygroups** [comment]
:+1:  I think it would be nice if one can use ohCrash like this:
`function myEnvFunc(){return 'whatever'}`
`require('ohcrash')('your API key', {env: myEnvFunc});`


Then down here ohCrash can have something like this:
`
var props = {
		runtime: this.options.env ? this.options.env() : envName()
	};
`

A check to ensur env is a function would be needed if env is should be strictly a function.


I'll be glad to PR this if you think its a good way to go.

**Comment by vadimdemedes** [comment]
Fixed in master.

You can do this via `globalProps`:

```js
require('ohcrash').register('endpoint', {
  globalProps: {
    env: 'development'
  }
});
```
