### ISSUE TITLE
Don't send the same error more than once

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ohcrash-client#5]

**Comment by frolic** [comment]
It might actually be beneficial to send more than once in case you want to aggregate on the server (e.g. count number of occurrences of a unique error).

**Comment by vadimdemedes** [comment]
Hm, yeah, I like that idea. I think the server could post comments to the related issue, like "This error has occurred more than 10 times" periodically (10, 50, 100, ...). That way server doesn't just modify issue body, which no one notices.
