### ISSUE TITLE
Don't polyfill Promise

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ohcrash-client#7]
Not. Good. https://github.com/vdemedes/ohcrash/blob/master/index.js#L17

**Comment by leewaygroups** [comment]
@vadimdemedes : I'm wondering why polyfilling promise in browser is not a good idea; please share.

Some developers and may users especially does in coporate environments with unyielding bureaucracy still run very old versions of IE on their machines.

I think not polyfilling may amount to penalising them.

**Comment by vadimdemedes** [comment]
> I'm wondering why polyfilling promise in browser is not a good idea; please share.

Because polyfills modify global environment, which means it actually affects all the code loaded in the page / Node.js process. Polyfills make modules bad citizens. Ponyfills are much better!

Closing this issue, since the new `ohcrash-client` is Node.js-only and doesn't use any polyfills.
