### ISSUE TITLE
Add the possibility to use OhCrash with repositories from Organizations

### ISSUE THREAD

**Issue by vrunoa** [vadimdemedes/ohcrash-client#9]
hey @vdemedes OhCrash seems great. I wanted to test it with a particular repository but this repository is on an Organization I manage, I wonder if you'll add the possibility to use OhCrash within this repositories.

**Comment by vadimdemedes** [comment]
First of all, glad you like it!

At the moment, this feature is disabled, because I wanted to release the first version as soon as possible. This is definitely on the roadmap for future releases. Thanks for the suggestion!

**Comment by vadimdemedes** [comment]
To clarify, at the moment only your own & public repositories are allowed.

**Comment by vrunoa** [comment]
Cool. I'll keep up to OhCrash news and wait for this feature to be released. :+1:

**Comment by vadimdemedes** [comment]
Feel free to use `ohcrash` with any GitHub repository now ;) Check out https://github.com/vadimdemedes/ohcrash for more info on how to set it up.
